### PR TITLE
Docs refactoring

### PR DESCRIPTION
**Pull request by MuhammadMuradG**
This PR will restructure the the docs directory hierarchy by adding some sections and enhancing the readability of `README.md` file.

### CODE REVIEW

**Review by Yuri-SVB — DISMISSED** [review]

**Comment by MuhammadMuradG** [comment]
The conflict must be resolved first before mergining it, I will resolve conflict today and I will notify you.

**Comment by MuhammadMuradG** [comment]
@Yuri-SVB Now, the conflicts have been resolved and adding removing unrelated settings in .gitignore file.

**Comment by AndreFGo** [comment]
If you let me, I should do some notes.
Tkinter is no longer required, it was in previous version, I've changed to PyQt5 package, version is bellow.
Keep the Icons folder in the git ignore, it is a temporary but necessary folder to store used icons, it will be removed in near future. If there's a better way to do this process of temporary files let me know please.
Also Pillow is required to create the icons, I'm not sure yet if it will be still required to manage the fractals in the next versions, either way it is required now.

I'm not sure if I should do these changes or let @MuhammadMuradG do it.

PyQt5 and Pillow versions are
PyQt5==5.15.10
Pillow==10.1.0

**Comment by MuhammadMuradG** [comment]
Hi, @AndreFGo 

> Tkinter is no longer required

I agree generally with you but as I can see, your suggestion to "removing Tkinter" is a separated task that is not direct related to this PR, so, I encourage you to open new Issue/PR that addresses the issue and what you suggest to solve it. This will help us to organize tasks...

> Keep the Icons folder in the git ignore, it is a temporary but necessary folder to store used icons, it will be removed in near future. If there's a better way to do this process of temporary files let me know please.

I have 2 concerns about that:
* If it's necessary folder to store icons, why you are ignoring adding the icons that you are using, if you are using some icons just let git add the icons to the project so other developers/contributors will be able using these icons and test the final appearance of the app.
* If it's temporary then I conservative about the names of files that you are used in the `.gitignore` file, these names, i.e. `*.png`, maybe used, as you mentioned, in the future to add some related files, like icons of some buttons, so if you want to test/experiment some features you can either use a path in your code that points to an outside path of the project or you can add these icons to some folder that is used conventionally to some junk files that is already created instead of using folders/files name that make sense to be related to the project itself, especially if it's temporally and we intend removing it, without strong reasons to do that with clarifying and documented that. Doing so may make the project hierarchy blowing, unclear and harder, especially if each developer do similar, to other developers/contributors in the development and testing processes.

> Also Pillow is required to create the icons, I'm not sure yet if it will be still required to manage the fractals in the next versions, either way it is required now.

I removed them unintentionally, I will commit to add them.

**Comment by MuhammadMuradG** [comment]
> based on user choices

Which means that it's user related configs and doesn't belong to the project, so, I prefer storing it in the user related folder like `Desktop` folder or `.local` folder or any similar folder.

> fractals is virtually infinity

This might make me suggest storing them in a `/tmp` folder if they are different on each new user app run.

**Pull request merged**
