### PR TITLE
Have iterations of the fractal formula be reused

### PR DESCRIPTION
**Pull request by turizspace**
issue #30 fix

### CODE REVIEW

**Comment by MuhammadMuradG** [comment]
Hi, @turizspace!

Could you please add a description of the approach that this PR follow? Also, the intention of the #30 was to enhance the performance of the app, so, is there an enhancement of performance? And can you give us a measure to this enhancement?

Last thing, we using a black with default configs to perform code formatting, so, keep stick with this please.

**Comment by turizspace** [comment]
@MuhammadMuradG      Approach Taken:
        Implemented a caching mechanism (_iteration_cache) to store intermediate results of points computed during fractal generation.
        The caching mechanism checks if a point has been computed. If so, it retrieves the cached value instead of recomputing it.

    Intention of Caching Mechanism:
        Enhance performance by avoiding redundant calculations during fractal generation.
        By storing intermediate results, previously computed values for points are reused, reducing computational overhead.

    Measuring Performance Enhancement:
        Compare the execution time of the application before and after implementing the caching mechanism.
        Use profiling tools or timing functions within Python to measure the time taken for fractal generation.
        Run the fractal generation code with and without caching multiple times and average the results to obtain a measure of performance enhancement.
        Additionally, compare memory usage before and after implementing the caching mechanism to ensure memory efficiency.

**Comment by MuhammadMuradG** [comment]
So, is there was a performance enhancement after you applying the PR? And could you please report the results; we want to make sure that there is a real improvement in performance?

**Comment by turizspace** [comment]
@MuhammadMuradG please run the code on your dev env i can see you are a collaborator you can test whether there is improvements or not.  I was asked to see the highway.  this chunk of code was handed in for free. My more than 25hrs of work on it were not compensated so i am not reporting anything back from here.  Thank you very much

**Comment by MuhammadMuradG** [comment]
In this project (Great Wall) we have a high standards that must be met before we merging code, specially because we are working on security, so, we are very conservative about merging codes without making sure it produces what we intend from it.

It is considered best practices and a measure of developers professionalism to add a description for their submitted PRs and in the case of adding performance enhancement it is necessary to describe how much the performance has been enhanced instead of saying/claiming that this PR do..... And as you choose to work on this it is expected from you and not from someone else to do that, especially and as you mentioned this small chunk of code took 25 Hrs from you which requires that you have plenty of time for this!!!

However, I run the code and it does not work and finally the application crashed!

**Comment by MuhammadMuradG** [comment]
We will close this as the contributor will not continue to complete the implementation, unfortunately.

Feel free to reopen it if you want to work on it.

**Comment by turizspace** [comment]
thank you for your time :) thank god it doesn't work I would have felt at a liss if it did and I wasn't paid $$ @MuhammadMuradG

**Comment by turizspace** [comment]
@MuhammadMuradG if you were so good at your job you guys would not need other developers! solving these issues that you guys can't even afford to pay contributors to do ! Also the last time i worked on this project the description actually ran the code . Now you have a NB saying it doesn't! 

You are all beneath me at this point if you want cheap labor just say so @Yuri-SVB  !! No need to pretend to be Bitcoiners and waste peoples time ! People who actually need the work but you want to pay them peanuts!  

If you were so good at what you do you guys would not need any help ! 🖕🏾🖕🏾🖕🏾🖕🏾

**Comment by MuhammadMuradG** [comment]
Thank you for taking the time to comment, it seems you have time for that. This project is a collaborative effort with a mixed contribution model. We value contributions from all skill levels. We welcome anyone who wants to contribute in a honest, positive and constructive way.

However, we will report your comment that contains expressions of contempt, sarcasm, obscene gestures and false claims not supported by evidence.

**Comment by turizspace** [comment]
You do that ! Then check merge history ! 

🫂🫂 i have time for everything but getting paid by people like you and your friends!

**Comment by turizspace** [comment]
You should all be ashamed of yourselves. Delete all the comments all you like. It's a shame @MuhammadMuradG @Yuri-SVB next time pay 💰 devs better @AndreFGo image gonna report this organization on bitcoinerjobs dot com

**Pull request closed without merging**
